### ISSUE TITLE
V2 - Response save active even on offline mode

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Queen#175]
🇫🇷 La sauvegarde des données au fil de l'eau est active, même en mode offline

🇬🇧 Responses are saved even on offline mode

**Comment by romaintailhurat** [comment]
In order to validate this feature, we need a proper back-office (→ Pearl embedding Queen).

**Comment by romaintailhurat** [comment]
Issue will be completed after those ones:

- #181 
- #178

**Comment by AnneHuSKa** [comment]
OK si sortie par arret mais KO si on est à la fin dans le questionnaire : on ne peut pas valider

**Comment by AnneHuSKa** [comment]
ok. Mode opératoire : connexion online à Sabiane ; ouverture d'un premier questionnaire contenant la nomenclature ; passage offline ; ouverture d'un autre questionnaire
