### ISSUE TITLE
Loop panel to be simplified

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Queen#185]
🇬🇧 (loose translation of the original post in french, see below)

When in a loop, we'd like to display a summary card for each iteration. Those cards helps with navigating the loop. 

What is described below is a simplification of the current behaviour.

How the cards work:
- they have an uppercase title, which is the value of the first collected variable of each iteration
- the background color of the card is blue for the current iteration, grey otherwise
- when an iteration has been passed, it becomes reachable, an arrow is displayed on the card itself. When clicking on a reachable card, the first page of the iteration is displayed. The current card is not clickable and doesn't have an arrow.

🇫🇷 (verbatim d'un ticket Trello créé par Quentin)

> Principe : dès qu'on se situe dans une boucle, on souhaite afficher à l'écran des cartes récapitulatives correspondant chacune à une itération de la boucle.
Ces cartes possèdent un titre et proposent de la navigation. Actuellement dans une carte on détaillait la réponse à toutes les variables associée à l'itération, on retire ce fonctionnel (mal pensé pour les QCU/QCM/missing...)
> Fonctionnement des cartes :
>    le titre de la carte correspond à la valeur de la première variable collectée associée à l'itération. Le titre est affiché en majuscule
>    --> ex en PJ : j'itère sur une boucle PRENOM dont la valeur de la première variable est ["Quentin", "Julie", "Paul"]
>    la carte correspondant à l'itération dans laquelle on se situe est affichée en bleu ; les autres en gris
>    --> ex en PJ : je me situe dans la 2e itération de la boucle, correspondant à "Julie"
 >   lorsque la première page d'une itération est atteignable (donc qu'on l'a déjà passée), sa carte est cliquable et une flèche est visible sur la carte. Le clic sur la carte permet alors de renvoyer vers la première page de l'itération. La carte de l'itération dans laquelle on se situe est non cliquable sans flèche
>    --> ex en PJ : je me situe actuellement dans l'itération "Julie", la carte est non cliquable sans flèche. Je peux revenir sur l'itération "Quentin" en cliquant sur la carte. Je n'ai pas commencé l'itération "Paul" donc non cliquable sans flèche. Si je reviens sur l'itération "Quentin", cette fois je pourrai revenir sur "Julie" car itération atteignable

**Comment by laurentC35** [comment]
Done & deployed
