### ISSUE TITLE
V2 - Long questions are masked by the loop panel

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Queen#186]
🇬🇧 Problem pushed by EdT survey: the loop panel is hiding part of a question label (a long one), see screenshots below.

🇫🇷 Problème transmis par l'enquête EdT: le panneau de boucle masque parfois le libellé de la question, voir les captures d'écran jointes.

![image](https://user-images.githubusercontent.com/1663283/206160487-548393af-761e-45b5-afc3-65eda6277408.png)
![image](https://user-images.githubusercontent.com/1663283/206160557-abd1e21e-d8e5-4693-a2be-ba3af40d8974.png)

**Comment by AnneHuSKa** [comment]
Toujours le cas en QueenV2

**Comment by AnneHuSKa** [comment]
corrigé en Queen V2 - juin 2023
