### ISSUE TITLE
V2 - Weird behaviour of the "Continue interview" / "Suite de l'entretien" button

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Queen#202]
:gb: In loops, the button "Suite de l'entretien" replaces the standard "Continuer" but without properly working. 

:fr: Dans les boucles, le bouton "Suite de l'entretien" remplace inopinément le bouton "Continuer" mais ne fonctionne pas.

**Comment by AnneHuSKa** [comment]
Queen 1.1.21 : ok
