### ISSUE TITLE
V2 - navigation NSP /refus dans le cas des boucles

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Queen#208]
Cas d'usage :
 - on est dans une boucle liée (exemple : description des habitants)
 - si on répond NSP ou refus à la question n, on passe directement à n+2. 
 - si on revient en arrière, la question n+1 s'affiche (donc comportement attendu).
Exemple dans le json joint :
-  répondre NSP ou refus à question 3, affiche la question 5, le retour arrière affiche la 4.
-  répondre NSP ou refus à question 4, affiche la question 6, le retour arrière affiche la 5.

https://visu-queen-v2-sandbox.demo.insee.io/queen/visualize?questionnaire=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fahusseini%2Fpublic%2FBugQueenNSPRefus.json

[Issue208_QueenNSPRefus.zip](https://github.com/InseeFr/Queen/files/11954986/Issue208_QueenNSPRefus.zip)

**Comment by laurentC35** [comment]
Le problème n'est pas liée à une boucle mais est dû à la combinaison de "NSP/Refus" avec une question de type Radio/CheckboxOne/CheckboxBoolean

**Comment by laurentC35** [comment]
La correction est disponible dans la version 1.0.7 de queen (visible sur sandbox)
